---
# Redmine
redmine_app_port: 80

# Datadog
datadog_site: "datadoghq.eu"

datadog_checks:
  process:
    init_config:
    instances:
      - name: ssh
        search_string: ['ssh', 'sshd']
      - name: syslog
        search_string: ['rsyslog']
        cpu_check_interval: 0.2
        exact_match: true
        ignore_denied_access: true
  http_check:
    init_config:
    instances:
      - name: Application health check status
        url: http://localhost:{{ redmine_app_port }}
        timeout: 5
        method: GET

datadog_api_key: "{{ vault_datadog_api_key }}"
