---
- name: Create .env For Containers
  template:
    src: env.j2
    dest: '.env'
  tags:
    - skip_ansible_lint

- name: Run Redmine Container
  docker_container:
    name: redmine
    image: redmine:{{ redmine_version }}
    state: started
    restart: true
    published_ports:
      - "{{ redmine_app_port }}:3000"
    env_file: .env
