---
- name: Update and upgrade apt packages
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400   # One day

- name: Include pip role
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
