---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Include pip role
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
